// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5FywiKXTnB1agGZma8H0wlcGq4Oc-fYk',
    appId: '1:755286485696:web:cc5eb906c473d4d7c21b25',
    messagingSenderId: '755286485696',
    projectId: 'ecommerceapp-7d86d',
    authDomain: 'ecommerceapp-7d86d.firebaseapp.com',
    storageBucket: 'ecommerceapp-7d86d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiDwlj8E4EBibhP3Z0OqbdkEHsL5zyYC8',
    appId: '1:755286485696:android:59f78a3bced58a9fc21b25',
    messagingSenderId: '755286485696',
    projectId: 'ecommerceapp-7d86d',
    storageBucket: 'ecommerceapp-7d86d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnfgzK_FX9-1iE4YvBF7GAEJpSWRWbuZ8',
    appId: '1:755286485696:ios:5b96c4d1d969094ec21b25',
    messagingSenderId: '755286485696',
    projectId: 'ecommerceapp-7d86d',
    storageBucket: 'ecommerceapp-7d86d.appspot.com',
    androidClientId: '755286485696-390pm3a7abin1648i7ke2rcqrccopi63.apps.googleusercontent.com',
    iosClientId: '755286485696-44m2i813m4bm2fv2gat0ovsb7m7m9ohk.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
